# config.yaml
paths:
  download_dir: 'YogaPoses'
  train_dir: 'data/train'
  val_dir: 'data/val'
  test_dir: 'data/test'

dataset:
  class_names: ["Downdog", "Goddess", "Plank", "Tree", "Warrior2"]
  batch_size: 32
  image_size: [256, 256]
  color_mode: 'rgb'
  seed: 99

training:
  num_epochs: 10
  learning_rate: 0.001
  dropout_rate: 0.5
