name: CI/CD Pipeline

# Define the event triggers for running the pipeline
on:
  push:
    branches:
      - main  # Run the pipeline on pushes to the main branch
  pull_request:
    branches:
      - main  # Run the pipeline on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # The type of runner (Ubuntu)

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs pull

    # Step 4: Run Tests
    - name: Run Tests
      run: |
        pytest tests/

    # Step 7: Train the models and log results (Optional)
    - name: Train Models
      run: |
        python train.py

    # # Step 8: Upload the Best Model as an Artifact
    # - name: Upload Best Model
    #   uses: actions/upload-artifact@v3  # Updated to v3
    #   with:
    #     name: best-model
    #     path: models/best_overall_model.weights.h5

    # Step 9: Upload Training Plots (Optional)
    - name: Upload Training Plots
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: training-plots
        path: plots/
